apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myvolumeclaim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: demo1
spec:
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: myvolumeclaim
  containers:
    - name: demo1
      image: trustysquirrel.azurecr.io/demo:v1
      volumeMounts:
        - mountPath: "/storage"
          name: myvolume